version: '3.7'

services:
  mysql-db:
    image: mysql/mysql-server:5.7
    container_name: ${DB_HOST}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_SERVER_PORT}:${DB_PORT}"
    expose:
      - ${DB_PORT}
    networks:
      - backend

  app:
    container_name: bizwhois-app
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - ./bizwhois-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SKIP_PREFLIGHT_CHECK=true
    tty: true
    links:
      - api
    depends_on:
      - api
    ports:
      - "${APP_SERVER_PORT}:${APP_SERVER_PORT}"
    expose:
      - ${APP_SERVER_PORT}
    networks:
      - frontend
      - backend

  api:
    container_name: bizwhois-api
    build:
      context: .
      dockerfile: api.dockerfile
      args:
        uid: ${UID}
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
#      - APACHE_RUN_USER=#${UID}
#      - APACHE_RUN_GROUP=#${UID}
      - APACHE_DOCUMENT_ROOT=/var/www/public
    volumes:
      - ./bizwhois-api:/var/www
    ports:
      - "${API_SERVER_PORT}:80"
    expose:
      - 80
    links:
      - ${DB_HOST}
    depends_on:
      - mysql-db
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
